### ISSUE TITLE
`e.len` does not work when using a model created with `create_model_from`

### ISSUE THREAD

**Issue by gAldeia** [folivetti/tir#6]
Hi,

In this function, when returning an individual from the front, I think it would be great to also have its size initialized:

https://github.com/folivetti/tir/blob/325f194fcfd4ddb723bf559c7ae30e0941617206/python/pyTIR/TIRRegressor.py#L130C1-L139C19

This is useful for calculating statistics with the population.

Is this something easy to fix?

**Comment by folivetti** [comment]
yes! It is done :-)

commit bc3ce95350116ffb0428691ce6ca2ef6ee8102b6
can you update in the srbench for me?

**Comment by gAldeia** [comment]
Sure! Thanks!

**Comment by gAldeia** [comment]
I just tested this new commit and it is working! Thanks for the fix.

Im stashing some commits regarding the srbench competition to avoid making everything public right now, but I'll update it soon.

I think we can close this issue!
